# Jekyll configuration for Canon documentation
# Uses Just the Docs theme - https://just-the-docs.com/

# Site settings
title: Canon Documentation
description: Semantic comparison for serialization formats (XML, HTML, JSON, YAML)
url: https://lutaml.github.io
baseurl: /canon

# Theme
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

# AsciiDoc support
asciidoc: {}
asciidoctor:
  attributes:
    - idprefix=_
    - source-highlighter=rouge
    - icons=font
    - experimental=''

# Build settings
plugins:
  - jekyll-asciidoc
  - jekyll-seo-tag

# Just the Docs theme configuration
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/

# Navigation
nav_sort: case_insensitive

# Footer content
footer_content: 'Copyright &copy; Ribose. <a href="https://opensource.org/licenses/BSD-2-Clause">BSD-2-Clause License</a>.'

# Color scheme - use light mode
color_scheme: light

# Logo
logo: false

# Aux links for the upper right navigation
aux_links:
  "Canon on GitHub":
    - "https://github.com/lutaml/canon"
  "Report Issue":
    - "https://github.com/lutaml/canon/issues"

# Aux links configuration
aux_links_new_tab: true

# Heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Collections - for organizing documentation
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Collection defaults
defaults:
  - scope:
      path: "docs"
      type: "docs"
    values:
      layout: "default"
      nav_exclude: false

# Only process documentation AsciiDoc files
include:
  - index.adoc

# Exclude everything except docs directory
exclude:
  - Gemfile
  - Gemfile.lock
  - Gemfile.docs
  - README.adoc
  - node_modules
  - vendor
  - lib
  - spec
  - bin
  - exe
  - pkg
  - sig
  - old-docs
  - .rspec
  - .rubocop.yml
  - .rubocop_todo.yml
  - .gitignore
  - Rakefile
  - canon.gemspec
  - .git
  - .github
  - "*.md"
  - "*.swp"
  - "*.tmp"
  - "**/*.md"
  - "!docs/**"

# Keep only AsciiDoc files in docs directory
keep_files:
  - "docs/*.adoc"
